blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/MrDwarf7/REPO_NAME/discussions
    about: When you have questions or need help, please visit our GitHub Discussions page.
